services:
  redis:
    image: "redis:8"
    container_name: dev_redis
    ports:
      - "6379:6379"

    volumes:
      - redis_dev_data:/data

    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      # - code and print a message, when the variable is not set or empty 
      # Source: https://stackoverflow.com/questions/68461172/docker-compose-redis-password-via-environment-variable
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    
    env_file:
      - .env

volumes:
  redis_dev_data: # Defines the named volume for data persistence
